# Generated by Django 4.1.3 on 2022-11-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='unid',
            new_name='uuid',
        ),
    ]
